## Lista de exercicios

In [1]:
# Imports
import numpy as np

In [2]:
# Matrizes
matriz1 = [[1, 2, 3], [0, 1, 4], [5, 6, 0]]
matriz2 = [[5, 2, 8], [3, 1, 2], [7, 0, 2]]

In [3]:
print(matriz1)
print(matriz2)

[[1, 2, 3], [0, 1, 4], [5, 6, 0]]
[[5, 2, 8], [3, 1, 2], [7, 0, 2]]


#### Ex. 1 Soma de Matrizes
Soma de matrizes com o mesmo tamanho. Lidas como listas, com e sem pacote Numpy

In [4]:
somamatrizes = matriz1 + matriz2
print(somamatrizes)


[[1, 2, 3], [0, 1, 4], [5, 6, 0], [5, 2, 8], [3, 1, 2], [7, 0, 2]]


In [5]:
somamtz = np.array(matriz1) + np.array(matriz2)
print(somamtz)

[[ 6  4 11]
 [ 3  2  6]
 [12  6  2]]


In [6]:
def somamtz_np (m1, m2):
    return np.array(m1) + np.array(m2)

In [7]:
somamtz_np(matriz1, matriz2)

array([[ 6,  4, 11],
       [ 3,  2,  6],
       [12,  6,  2]])

#### Ex.2 Multiplicação de Matrizes
Multiplica duas matrizes. Verifica se as dimensões são compatíveis, e retorna a matriz resultante.

In [9]:
prod_mtz = np.matmul(matriz1, matriz2)
print(prod_mtz)

[[32  4 18]
 [31  1 10]
 [43 16 52]]


In [10]:
dot_mtz = np.dot(matriz1, matriz2)
print(dot_mtz)

[[32  4 18]
 [31  1 10]
 [43 16 52]]


In [13]:
cross_mtz = np.cross(matriz1, matriz2)
print(cross_mtz)

[[ 10   7  -8]
 [ -2  12  -3]
 [ 12 -10 -42]]


#### Ex. 3 Transposição de Matriz
Calcula a transposta de uma matriz. Uma matriz inserida pelo usuário, e o resultado da transposta é exibido.

In [16]:
tp_mtz = np.transpose(matriz1)
print(tp_mtz)

[[1 0 5]
 [2 1 6]
 [3 4 0]]


In [19]:
def transposta_matriz(matriz):
    return np.transpose(matriz)

In [17]:
x = matriz1
y = matriz2

In [20]:
transposta_matriz(x)

array([[1, 0, 5],
       [2, 1, 6],
       [3, 4, 0]])

In [21]:
transposta_matriz(y)

array([[5, 3, 7],
       [2, 1, 0],
       [8, 2, 2]])

#### Ex. 4 Traço de uma Matriz
Soma dos elementos da diagonal principal. Matrizes quadradas de qualquer tamanho.

In [22]:
def traco_matriz(matriz):
    return np.trace(matriz)

In [25]:
traco_matriz(matriz1)

2

In [24]:
traco_matriz(matriz2)

8

#### Ex. Determinante de uma Matriz
Calculo determinantes de uma matriz quadrada. Recursividade ou método laplace.

In [26]:
def determinante_matriz(matriz):
    return np.linalg.det(matriz)

In [27]:
determinante_matriz(matriz1)

0.9999999999999987